### ISSUE TITLE
MoU13: m3 complete "New TeraReceiver code for encrypted downloads"

### ISSUE THREAD

**Issue by monkeyiq** [filesender/governance#20]
In https://github.com/filesender/filesender/pull/1156 a new TeraReceiver mode is introduced and optionally used to download encrypted files using a single web worker.  The core of this milestone is moving from the callback style to using the TeraSender manager object to administer a web worker to perform the actual chunk download. This required update to not only the callback flow but also to progress and error handling to work from a web worker context rather than the primary browser thread.

**Comment by meijer** [comment]
Quoting milestone text: 
_"FileSender currently uses a configurable number of web workers during upload in order to keep the network loaded. This milestone will introduce a new TeraReceiver mode allowing chunks of a file to be download in web workers. This TeraReceiver mode will optionally be used for encrypted downloads, both single file downloads and during the creation of zip64 files for selected encrypted files. This involves moving from a purely callback single threaded download code path to using a manager class to handle web workers and pass data, progress, and error information correctly.

This milestone is limited to using a single web worker, so only one chunk downloading at a time. This will pave the way for future updates allowing multiple chunks being downloaded (a second milestone), and moving decryption into the web workers (a subsequent milestone). With all milestones in place the final result will be multitheaded download and decryption of file content.

Delivery of milestone: A release with the option to use a TeraReceiver mode for downloading encrypted files."_
Milestone delivery checked, acceptance recommended to the board and called for vote. Happy to see this option becoming available, now that FileSender supports unlimited downloads of encrypted files (since the streaming download update a while back) putting us on the path to speeding up those downloads is a good improvement, thanks! 

One question: once all TeraReceiver milestones would be done, would you say it would be prudent to explicitly check the security status of crypto with a security audit, possibly limited to the crypto functionality?

**Comment by meijer** [comment]
Board voted for acceptance: unanimous in favour. Milestone accepted. Mail with request to initiate payment sent to NLnet.

**Comment by monkeyiq** [comment]
Payment received, thank you.
