### ISSUE TITLE
MoU13 m2a complete "Selenium Continuous Integration test update (part a)"

### ISSUE THREAD

**Issue by monkeyiq** [filesender/governance#22]
The Selenium tests ConfigurationOptionsTest.php, EncryptionTest.php, TransferExpiredTest.php, and UploadAutoResumeTest.php have been updated and refreshed for the bootstrap UI in the development3 branch. New methods have been introduced to make the processing both faster and more robust by waiting for explicit elements to be displayed before progressing.

https://github.com/filesender/filesender/pull/1157

A number of small updates to 1157 were also merged as well as a number of testing only CI PR runs created resulting in a final test run which passes on Sauce Labs (https://github.com/filesender/filesender/pull/1174)

https://github.com/filesender/filesender/pull/1158
https://github.com/filesender/filesender/pull/1159
https://github.com/filesender/filesender/pull/1160
https://github.com/filesender/filesender/pull/1161
https://github.com/filesender/filesender/pull/1162
https://github.com/filesender/filesender/pull/1163
https://github.com/filesender/filesender/pull/1164
https://github.com/filesender/filesender/pull/1165
https://github.com/filesender/filesender/pull/1166
https://github.com/filesender/filesender/pull/1167
https://github.com/filesender/filesender/pull/1168
https://github.com/filesender/filesender/pull/1169
https://github.com/filesender/filesender/pull/1171
https://github.com/filesender/filesender/pull/1172
https://github.com/filesender/filesender/pull/1173
https://github.com/filesender/filesender/pull/1174

**Comment by meijer** [comment]
Milestone as defined in MoU:

_"FileSender includes 10 unit tests which use Selenium to control a web browser to verify expected functionality and expected failure of the system. The Selenium tests are run with Sauce Labs to verify that proposed updates in pull requests do not break system functionality.
This milestone will update the listed tests to function on the FileSender 3.x alpha (using Bootstrap for UI). In addition to updating to cater for the user interface the Selenium tests should be refreshed to use busy waits where possible. Currently the test system contains many race conditions which are only resolved by explicitly waiting longer than needed before continuing. It is proposed to instead inspect the web page for elements and visibility and/or use javascript to determine explicitly if the web browser is presenting an expected state.

Deliverable: 
• A release with the ConfigurationOptionsTest.php, EncryptionTest.php, TransferExpiredTest.php, UploadAutoResumeTest.php test cases updated as described."_

Milestone delivery checked, acceptance recommended to the board and called for vote. Glad to see this update, as I understood it the test infrastructure really needed this update. Am I correct that if anyone would want to know exactly what is being tested, they'd have to look in the code of the selenium tests? 

For the audience: a bit of history and information about our testing policy. We need a good quality FileSender product for multiple reasons: 
1. the obvious one that all people using the software want to have a smooth experience
2. less obvious: FileSender is a service for the masses. Dealing with user trouble is expensive for a service provider, and none of the FIleSender service providers (our stakeholders) has the resources to really deal with substantial numbers of issues, so when a new filesender version is released, the core functionality simply needs to work for the vast majority of people. Acceptable issues are those that are corner cases, as they are hard to catch whether you test automatically or manually, and due to browser and desktops changing all the time, corner cases also change
3. the FileSender development effort is small. We can't deal with large numbers of bugs, and sufficient automated testing of core functionality is a very effective way to not have to deal with large numbers of bugs.

This policy has served us well over the past decade, but in the start had one drawback: we were testing largely manually which led to long lead times for new releases. That's why we changed to automated testing. This means the FileSender code will ALWAYS perform core functionality after a commit, meaning we always release deployable code. Now we're learning what the maintenance cost of the automated testing infrastructure is. 

Automated testing is one core pillar of our quality assurance, the other one is field testing and has been from day one. As a service targeting a large heterogenous user base in an ecosystem where we know browser preference differs from country to country, we can't predict up front exactly where trouble is going to come from. There's only one way to find out: test it. From our large footprint we have a number of sites willing to trial releases and put load on them at an early stage. That tends to flesh out any corner cases.

**Comment by meijer** [comment]
Board voted for acceptance: unanimous in favour. Milestone accepted.

**Comment by monkeyiq** [comment]
Payment received, thank you.
