### ISSUE TITLE
Defaults: email_from/email_return_path sender still best?

### ISSUE THREAD

**Issue by monkeyiq** [filesender/governance#38]
An issue on the regular FileSender issue tracker is asking about possibly changing the default values for email_from to a static no reply address.  https://github.com/filesender/filesender/issues/1820

I am happy to update these defaults for the 3.x series to allow less work for system admins who might otherwise have to try to workout ways for the system to allow emails from other domains or other issues.

**Comment by WebSpider** [comment]
In the days of more strict spam combatting, using the sender address of the user makes it a lot more complex, since the mail relay would need to do all the fancy DKIM signatures as well.

Looking at the [current documentation](https://docs.filesender.org/filesender/v2.0/admin/configuration/#email_from), this currently has no default. This in itself is interesting, since an e-mail has to have a from-address, so I guess the actual default here is related to the php config.

I guess it doesn't hurt to change the default to something like `noreply$cfg:site_url` or something similar, making it independant of the php config, which the filesender admin doesn't need to have access to directly

**Comment by meijer** [comment]
Board consensus: changing defaults sounds like a good idea, we suggest to leave it to the two of you whether to implement @WebSpider 's suggestion or go for something else. Just if you're going for something else, "no-reply@no-domain.dom" might have future consequences ;) Closing the governance ticket.
